<?php

    $permissions = array(
        '/'                 => 0,
        '/messages/'        => 50,
		'/messages/dialog'	=> 50,
        '/token/'           => 50,
        '/settings/'        => 25,
        '/news/'            => 0,
		'/news/post'		=> 0,
		'/news/commentcreate' => 50,
		'/news/commentdelete' => 50,
		'/news/commentrestore' => 50,
		'/news/commentupdate' => 50,
        '/news/add'         => 150,
		'/news/delete'		=> 150,
		'/news/restore'		=> 150,
		'/news/edit'		=> 150,
		'/news/update'		=> 150,
        '/news/create'      => 150,
        '/feedback/'        => 25,
        '/feedback/new'     => 25,
        '/feedback/create'  => 25,
        '/feedback/active'  => 150,
    );